local Scene = require "engine.Scene"
local cacheManager = require "engine.cacheManager"
local glyphs = require "engine.input.glyphs"

--- Preloads everything the examples share. Registered first in every
--- runner-built Game, so examples never preload assets themselves (a second
--- preload of the same key is an error in cacheManager).
---
--- Fonts follow the engine contract (header/subheader/body/small). The two
--- example sheets are generated by `love . --gen-assets` (see genassets.lua).
---@class ExamplesPreload : Scene
local ExamplesPreload = Scene.extend(Scene)

ExamplesPreload.GHOST_SHEET = "examples-ghost"
ExamplesPreload.GHOST_PATH = "examples/assets/ghost.png"
ExamplesPreload.GHOST_FRAMES = { "float1", "float2", "float3", "float4", "wave1", "wave2", "wave3", "wave4" }
ExamplesPreload.TILES_SHEET = "examples-tiles"
ExamplesPreload.TILES_PATH = "examples/assets/tiles.png"
ExamplesPreload.TILE_FRAMES = { "grass", "dirt", "stone", "water" }
ExamplesPreload.TILE = 16

function ExamplesPreload:new()
  ExamplesPreload.super.new(self, "examples/preload")
end

function ExamplesPreload:load()
  if cacheManager.hasFont("body") then return end -- already preloaded (hot reload keeps the cache)
  cacheManager.preloadFont("header", "assets/fonts/PixelOperator8.ttf", 24)
  cacheManager.preloadFont("subheader", "assets/fonts/PixelOperator8.ttf", 20)
  cacheManager.preloadFont("body", "assets/fonts/PixelOperator8.ttf", 16)
  cacheManager.preloadFont("small", "assets/fonts/PixelOperator8.ttf", 12)
  cacheManager.preloadImage(glyphs.IMAGE_KEY, glyphs.IMAGE_PATH)
  if love.filesystem.getInfo(ExamplesPreload.GHOST_PATH) then
    cacheManager.preloadSpritesheet(ExamplesPreload.GHOST_SHEET, ExamplesPreload.GHOST_PATH,
      ExamplesPreload.TILE, ExamplesPreload.TILE, ExamplesPreload.GHOST_FRAMES)
    cacheManager.preloadImage("examples-ghost-image", ExamplesPreload.GHOST_PATH)
  end
  if love.filesystem.getInfo(ExamplesPreload.TILES_PATH) then
    cacheManager.preloadSpritesheet(ExamplesPreload.TILES_SHEET, ExamplesPreload.TILES_PATH,
      ExamplesPreload.TILE, ExamplesPreload.TILE, ExamplesPreload.TILE_FRAMES)
    cacheManager.preloadImage("examples-tiles-image", ExamplesPreload.TILES_PATH)
  end
end

return ExamplesPreload
